import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Autogenerate from the folder you point docs.path at
  reference: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
